---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-demo-cluster-service
  labels:
    app: cassandra-demo-cluster
  namespace: pks-workshop
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra-demo-cluster-app
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-demo-cluster-external
  labels:
    app: cassandra-demo-cluster
  namespace: pks-workshop
spec:
  type: LoadBalancer
  ports:
    - port: 9042
  selector:
    app: cassandra-demo-cluster-app
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: cassandra-demo-cluster-app
  labels:
    app: cassandra-demo-cluster
  namespace: pks-workshop
spec:
  serviceName: cassandra-demo-cluster-service
  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra-demo-cluster-app
    spec:
      containers:
      - name: cassandra
        image: cassandra:3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 4096Mi
          requests:
            cpu: "1"
            memory: 4096Mi
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        env:
          - name: CASSANDRA_SEEDS
            value: cassandra-demo-cluster-app-0.cassandra-demo-cluster-service.pks-workshop.svc.cluster.local
          - name: MAX_HEAP_SIZE
            value: 1024M
          - name: HEAP_NEWSIZE
            value: 734M
          - name: CASSANDRA_CLUSTER_NAME
            value: "Cassandra"
          - name: CASSANDRA_DC
            value: "DC1"
          - name: CASSANDRA_RACK
            value: "Rack1"
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: GossipingPropertyFileSnitch
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra/data
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 30Gi
